import numpy as np
import math
import sys
import json
from bitstring import *

ifile = open("in.tex", "r")
m = ifile.read()
ifile.close()

W = 2**8 - 1
L = 2**8 - 1
W_bits = math.ceil(math.log(W + 1, 2))
L_bits = math.ceil(math.log(L + 1, 2))
character_bits = 16
max_character_bits = 8

def binary_to_characters(m):
	while len(m) % max_character_bits != 0:
		m = m + '0'
	ret = ""
	i = 0
	while i < len(m):
		ret += chr(int(m[i : i + max_character_bits], 2))
		i += max_character_bits
	ret += chr(int(m[i - max_character_bits:], 2))
	return ret

def characters_to_binary(m):
	ret = ""
	for i in m:
		b = np.binary_repr(ord(i))
		if len(b) < max_character_bits:
			b = ("0" * int(max_character_bits - len(b))) + b
		ret += b
	return ret

def lz77_encode(m):
	"""Returns an array of triples generated by running LZ77 on a message m"""
	i = 0
	ret = ""
	while i < len(m):
		best_d = 0
		best_l = 0
		for d in range(1, min(W, i + 1)):
			l = 1
			while l <= L and l < d and i + l < len(m) and m[i + l - 1] == m[i - d + l - 1]:
				l += 1
			if l - 1 > best_l:
				best_l = l - 1
				best_d = d
		d = np.binary_repr(best_d)
		l = np.binary_repr(best_l)
		c = np.binary_repr(ord(m[i + best_l]))
		while len(d) < W_bits:
			d = '0' + d
		while len(l) < L_bits:
			l = '0' + l
		while len(c) < character_bits:
			c = '0' + c
		ret += d + l + c
		i += best_l + 1
	return ret

enc = lz77_encode(m)
ofile = open('file.bin', 'wb')
BitArray(bin=enc).tofile(ofile)
ofile.close()